### ISSUE TITLE
Branch support

### ISSUE THREAD

**Issue by s1hofmann** [FauDroids/MrHyde#29]
Supporting branches would allow to work with blogs hosted in a separate gh-pages branch

**Comment by Haroenv** [comment]
Is there some way I can help with this?

**Comment by Maddoc42** [comment]
Actually yes. There are two goals for this issue:

1) short term: use the default git head for repos instead of assuming "heads/master" as default. This solves your immediate problem (gh-pages is the default in that case) but does not give users control over which branch they would like to work on.
2) long term: ability to switch between branches "dynamically"

For 1) this means getting the default head (if the GitHub API supports that. If not just get the first valid head) in https://github.com/FauDroids/MrHyde/blob/master/client/app/src/main/java/org/faudroids/mrhyde/git/FileManager.java#L420 and replacing the "heads/master" in that file.

If you want to just send us a pull request, I'd be happy to assist if there are any questions etc.

**Comment by Maddoc42** [comment]
Part of the upcoming release, checkout https://play.google.com/apps/testing/org.faudroids.mrhyde

**Comment by Maddoc42** [comment]
Released as v1.0.0.
